const SAMPLE=`The Girl From Next Door\nTraditional / Demo\nKey: F\n\nVerse:\n   Fmaj7          G7          Gm7         C7\nTall and tan and young and lovely\n`;
const AMAZING=`Amazing Grace\nJohn Newton\nKey: G\n\nVerse 1:\n[G]Amazing [G7]grace, how [C]sweet the [G]sound\nThat saved a wretch like [D]me\nI [G]once was [G7]lost, but [C]now am [G]found\nWas [Em]blind, but [D]now I [G]see\n`;
let state={raw:SAMPLE,parsed:null,styled:null,style:"bossa",density:2};
const $=s=>document.querySelector(s);
function renderStyleButtons(){const box=$("#styles");box.innerHTML="";Object.values(STYLES).forEach(st=>{const b=document.createElement("button");b.className="style"+(state.style===st.id?" on":"");b.innerHTML=`<b>${st.name}</b><small>${st.tags.join(" · ")}</small>`;b.onclick=()=>{state.style=st.id;renderStyleButtons();restyle();};box.appendChild(b);});}
function renderDensity(){$("#dens").querySelectorAll("button").forEach(b=>b.classList.toggle("on",Number(b.dataset.d)===state.density));}
function parseCurrent(){state.parsed=parseSongText(state.raw);restyle();}
function restyle(){if(!state.parsed)state.parsed=parseSongText(state.raw);state.styled=applyStyleToSong(state.parsed,state.style,state.density);renderChart();}
function renderChart(){const song=state.styled;const m=song.meta;$("#titleOut").textContent=m.title||"Untitled chart";$("#byOut").textContent=[m.artist,m.author].filter(Boolean).join(" — ");$("#badgeKey").textContent="Key "+(m.key||"?");$("#badgeStyle").textContent=m.style||STYLES[state.style].name;const body=$("#chartBody");body.innerHTML="";for(const sec of song.sections){if(sec.name){const h=document.createElement("div");h.className="section-name";h.textContent=sec.name;body.appendChild(h);}for(const line of sec.lines){if(line.type==="blank")continue;const row=document.createElement("div");row.className="lyric-block";(line.parts||[]).forEach(p=>{const wrap=document.createElement("span");wrap.className="pair";const ch=document.createElement("span");ch.className="ch"+(p.generated?" gen":"");ch.textContent=p.chord||"\u00a0";const ly=document.createElement("span");ly.className="ly";ly.textContent=p.lyric||"";wrap.append(ch,ly);row.appendChild(wrap);});body.appendChild(row);}}}
function downloadText(filename,text){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/plain"}));a.download=filename;a.click();}
function slug(s){return (s||"chart").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");}
function handleFiles(files){const file=files&&files[0];if(!file)return;if(file.name.toLowerCase().endsWith(".pdf")){loadPdf(file);return;}const r=new FileReader();r.onload=()=>{state.raw=String(r.result||"");$("#src").value=state.raw;parseCurrent();};r.readAsText(file);}
async function loadPdf(file){if(!window.pdfjsLib){alert("PDF engine still loading");return;}const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;let text="";for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i);const content=await page.getTextContent();text+=extractTextFromPdfItems(content.items)+"\n\n";}state.raw=text.trim()+"\n";$("#src").value=state.raw;parseCurrent();}
function wire(){renderStyleButtons();renderDensity();$("#src").value=state.raw;$("#dens").onclick=e=>{const b=e.target.closest("button");if(!b)return;state.density=Number(b.dataset.d);renderDensity();restyle();};$("#src").addEventListener("input",e=>state.raw=e.target.value);$("#go").onclick=parseCurrent;$("#sampleBossa").onclick=()=>{state.raw=SAMPLE;$("#src").value=SAMPLE;state.style="bossa";renderStyleButtons();parseCurrent();};$("#sampleGrace").onclick=()=>{state.raw=AMAZING;$("#src").value=AMAZING;state.style="gospel";renderStyleButtons();parseCurrent();};$("#dlCho").onclick=()=>{if(!state.styled)parseCurrent();downloadText(slug(state.styled.meta.title)+".cho",toChordPro(state.styled));};$("#dlOnsong").onclick=()=>{if(!state.styled)parseCurrent();downloadText(slug(state.styled.meta.title)+".onsong",toOnSong(state.styled));};$("#dlTxt").onclick=()=>{if(!state.styled)parseCurrent();downloadText(slug(state.styled.meta.title)+"-chart.txt",toAlignedChart(state.styled));};$("#printBtn").onclick=()=>window.print();const drop=$("#drop"),file=$("#file");drop.onclick=()=>file.click();file.onchange=()=>handleFiles(file.files);drop.addEventListener("drop",e=>{e.preventDefault();handleFiles(e.dataTransfer.files);});["dragover","dragenter"].forEach(ev=>drop.addEventListener(ev,e=>e.preventDefault()));parseCurrent();}
document.addEventListener("DOMContentLoaded",wire);
