const NOTES=["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"];
const FLATS=["C","Db","D","Eb","E","F","Gb","G","Ab","A","Bb","B"];
function noteIndex(name){if(!name)return 0;let n=String(name).replace("♯","#").replace("♭","b");const i=NOTES.indexOf(n);if(i>=0)return i;const j=FLATS.indexOf(n);return j>=0?j:0;}
function pitchName(idx,flats){idx=((idx%12)+12)%12;return flats?FLATS[idx]:NOTES[idx];}
function preferFlatsForKey(root,minor){if(/b|♭/.test(root))return true;if(/#/.test(root))return false;return minor?["D","G","C","F","Bb","Eb","Ab"].includes(root):["F","Bb","Eb","Ab","Db","Gb","Cb"].includes(root);}
function parseChord(raw){if(!raw)return null;let s=String(raw).trim().replace(/♯/g,"#").replace(/♭/g,"b").replace(/\s+/g,"");if(!s||s==="N.C."||s==="NC")return {raw,root:null,quality:"nc",ext:"",bass:null,kind:"nc"};const slash=s.split("/");const main=slash[0];const bass=slash[1]||null;const m=main.match(/^([A-G]|H)([#b]?)(.*)$/);if(!m)return {raw,root:null,quality:"unk",ext:main,bass,kind:"unk"};let root=m[1]==="H"?"B":m[1];if(m[2])root+=m[2];let rest=(m[3]||"").replace(/^[-]/,"m").replace(/min/gi,"m").replace(/Δ|∆/g,"maj").replace(/M(?=\d|$)/g,"maj").replace(/ø/g,"m7b5").replace(/°/g,"dim").replace(/o(?=\d|$)/g,"dim");let kind="maj";if(/^m7b5/.test(rest))kind="m7b5";else if(/^dim|^o/.test(rest))kind="dim";else if(/^aug|^\+/.test(rest))kind="aug";else if(/^sus2/.test(rest))kind="sus2";else if(/^sus/.test(rest))kind="sus4";else if(/^m(?!aj)/.test(rest))kind="min";else if(/^7|^9|^11|^13|^alt/.test(rest))kind="dom";else if(/^maj/.test(rest)||rest===""||/^6|^add|^2$|^5$/.test(rest))kind="maj";return {raw,root,quality:rest,ext:rest,bass,kind};}
function formatChord(ch,flats){if(!ch||ch.kind==="nc")return "N.C.";if(!ch.root)return ch.raw||"";let out=pitchName(noteIndex(ch.root),flats)+(ch.quality||"");if(ch.bass)out+="/"+pitchName(noteIndex(ch.bass),flats);return out;}
function interval(a,b){return (noteIndex(b)-noteIndex(a)+12)%12;}
function guessKey(chords,metaKey){if(metaKey){const cleaned=metaKey.trim().replace(/major/i,"").replace(/minor/i,"m").trim();const minor=/m$|min/i.test(cleaned)&&!/maj/i.test(cleaned);const p=parseChord(cleaned);if(p&&p.root)return {root:p.root,minor,source:"meta"};}const usable=chords.filter(c=>c&&c.root);if(!usable.length)return {root:"C",minor:false,source:"default"};const last=usable[usable.length-1];if(last.kind==="maj"||last.kind==="min")return {root:last.root,minor:last.kind==="min",source:"last"};return {root:usable[0].root,minor:usable[0].kind==="min",source:"first"};}
function iiOf(t,f){return {root:pitchName(noteIndex(t)+2,f),quality:"m7",ext:"m7",bass:null,kind:"min"};}
function vOf(t,f){return {root:pitchName(noteIndex(t)+7,f),quality:"7",ext:"7",bass:null,kind:"dom"};}
function enrichQuality(ch,style,role){if(!ch||!ch.root)return ch;const c={...ch};const paint={bossa:{maj:role==="tonic"?"maj9":"maj7",min:"m9",dom:"9"},"smooth-jazz":{maj:"maj9",min:"m11",dom:role==="cadence"?"13":"9"},gospel:{maj:"2",min:"m7",dom:"7"},"neo-soul":{maj:"maj9",min:"m9",dom:"7sus4"},"pop-ballad":{maj:"add9",min:"m7",dom:"sus4"},funk:{maj:"maj7",min:"m7",dom:"9"},blues:{maj:"7",min:"m7",dom:"7#9"},latin:{maj:"maj7",min:"m7",dom:"7"},rnb:{maj:"maj7",min:"m7",dom:"9"},worship:{maj:"2",min:"m7",dom:"sus"},country:{maj:"",min:"m",dom:"7"}};const map=paint[style]||paint.bossa;if(!c.quality||/^(m|maj|7|sus4|sus)?$/.test(c.quality)){c.quality=map[c.kind]!==undefined?map[c.kind]:c.quality;c.ext=c.quality;}else if(style==="smooth-jazz"||style==="bossa"||style==="neo-soul"){if(c.quality==="maj7")c.quality=c.ext="maj9";else if(c.quality==="m7")c.quality=c.ext=style==="smooth-jazz"?"m11":"m9";else if(c.quality==="7"){c.quality=c.ext=style==="smooth-jazz"?"13":"9";c.kind="dom";}}return c;}
function passingBetween(prev,next,key,style,density,flats){if(!prev||!next||!prev.root||!next.root||density<=0)return [];if(noteIndex(prev.root)===noteIndex(next.root))return [];const iv=interval(prev.root,next.root);const out=[];const addIIV=()=>{out.push(iiOf(next.root,flats));const v=vOf(next.root,flats);if(style==="smooth-jazz"||style==="bossa"){v.quality=v.ext=density>=3?"13":"9";}out.push(v);};if(style==="bossa"||style==="latin"||style==="smooth-jazz"||style==="rnb"||style==="neo-soul"){if(iv!==0){if(density>=2)addIIV();else out.push(density>=1?iiOf(next.root,flats):null);}}else if(style==="gospel"||style==="blues"){if(iv===5)out.push({root:prev.root,quality:"7",ext:"7",bass:null,kind:"dom"});else if(density>=2)out.push({root:pitchName(noteIndex(next.root)+1,flats),quality:"dim7",ext:"dim7",bass:null,kind:"dim"});}const cap=density===1?1:density===2?2:3;return out.filter(Boolean).slice(0,cap).map(c=>({...c,generated:true}));}
function roleFor(ch,key){if(!ch||!ch.root)return "other";const iv=interval(key.root,ch.root);if(iv===0)return "tonic";if(iv===7||ch.kind==="dom")return "cadence";if(iv===5)return "subdom";return "other";}
const STYLES={bossa:{id:"bossa",name:"Bossa Nova",blurb:"ii–V–I, maj9 / m9 / 13.",tags:["ii–V–I","maj9","tritone"]},"smooth-jazz":{id:"smooth-jazz",name:"Smooth Jazz",blurb:"9 / 11 / 13 and secondary dominants.",tags:["13","m11","slash"]},gospel:{id:"gospel",name:"Gospel",blurb:"Walk-ups, I7→IV, passing dim.",tags:["walk-up","dim","I7"]},"neo-soul":{id:"neo-soul",name:"Neo-Soul",blurb:"maj9, m9, 7sus4.",tags:["m11","7sus4","color"]},"pop-ballad":{id:"pop-ballad",name:"Pop Ballad",blurb:"add9 and sus.",tags:["add9","sus","space"]},funk:{id:"funk",name:"Funk",blurb:"9 and 7#9.",tags:["9","7#9","sus"]},blues:{id:"blues",name:"Blues",blurb:"Dominant I–IV–V.",tags:["7","7#9","dim"]},latin:{id:"latin",name:"Latin / Samba",blurb:"maj7 / m7 with ii–V.",tags:["maj7","ii–V","samba"]},rnb:{id:"rnb",name:"R&B",blurb:"maj7, m7, applied V.",tags:["maj7","V/x","walk"]},worship:{id:"worship",name:"Worship",blurb:"add2 and sus holds.",tags:["2","sus","IV/I"]},country:{id:"country",name:"Country",blurb:"Triads with I7 and vi.",tags:["triads","I7","vi"]}};
