const SECTION_RE=/^(verse|chorus|bridge|intro|outro|pre-chorus|prechorus|tag|coda|ending|refrain|hook)(\s*\d+)?\s*:?\s*$/i;
const META_RE=/^(title|artist|author|key|tempo|time|capo)\s*:\s*(.+)$/i;
const CHORDPRO_META=/^\{\s*(title|t|subtitle|st|artist|key|k|tempo|comment|c)\s*:\s*(.+?)\s*\}$/i;
const TOKEN_CHORD=/^[A-H](?:#|b)?(?:maj|min|m(?!aj|[a-z])|sus|add|dim|aug|\+|-)?(?:[0-9]+|#\d+|b\d+|sus[24]?|add[0-9]+|maj7|maj9|#9|b9|#11|b13)*?(?:\/[A-H](?:#|b)?)?$/i;
function looksLikeChord(tok){if(!tok)return false;const t=tok.replace(/[()]/g,"").trim();if(t==="N.C."||t==="NC")return true;if(/^(And|An|At|As|All|I|In|If|It|Is|On|Or|Of|Oh|Do|Go|So|No|We|He|Me|My|To|Be)$/i.test(t))return t==="A"||t==="E";if(!/^[A-H][#b]?/.test(t))return false;if(t.length>14)return false;if(/[aeiouy]{2,}/i.test(t)&&!/maj|sus|dim|aug|min|add/.test(t))return false;return TOKEN_CHORD.test(t);}
function isChordLine(line){const t=line.trim();if(!t||/\[/.test(line))return false;const parts=t.split(/\s+/).filter(Boolean);return parts.length&&parts.every(looksLikeChord);}
function parseBracketLine(line){const parts=[];const re=/\[([^\]]+)\]/g;let last=0,m;while((m=re.exec(line))){if(m.index>last)parts.push({lyric:line.slice(last,m.index),chord:null});parts.push({lyric:"",chord:m[1].trim(),pending:true});last=m.index+m[0].length;}if(last<line.length)parts.push({lyric:line.slice(last),chord:null});const merged=[];for(const p of parts){if(p.pending)merged.push({chord:p.chord,lyric:""});else if(merged.length&&merged[merged.length-1].lyric===""&&merged[merged.length-1].chord)merged[merged.length-1].lyric=p.lyric;else merged.push({chord:p.chord,lyric:p.lyric});}return merged;}
function snapToWordStart(text,col){if(col<=0)return 0;if(col>=text.length)return text.length;if(text[col]!==" "&&text[col-1]!==" "){let i=col;while(i>0&&text[i-1]!==" ")i--;return i;}if(text[col]===" "){let i=col;while(i<text.length&&text[i]===" ")i++;return i;}return col;}
function parseChordsOverLyrics(chordLine,lyricLine){const chords=[];const re=/\S+/g;let m;while((m=re.exec(chordLine))){if(looksLikeChord(m[0]))chords.push({chord:m[0],col:m.index});}if(!chords.length)return [{chord:null,lyric:lyricLine}];const snapped=chords.map((c,i)=>{let col=snapToWordStart(lyricLine,c.col);if(i===0&&col>0&&col<=3)col=0;return {chord:c.chord,col};});for(let i=1;i<snapped.length;i++){if(snapped[i].col<=snapped[i-1].col)snapped[i].col=Math.min(lyricLine.length,snapped[i-1].col+1);}const parts=[];for(let i=0;i<snapped.length;i++){const start=snapped[i].col;const end=i+1<snapped.length?snapped[i+1].col:lyricLine.length;if(i===0&&start>0)parts.push({chord:null,lyric:lyricLine.slice(0,start)});parts.push({chord:snapped[i].chord,lyric:lyricLine.slice(Math.min(start,lyricLine.length),Math.min(end,lyricLine.length))});}return parts;}
function parseMetaLine(line,meta){const cp=line.match(CHORDPRO_META);if(cp){const map={t:"title",st:"artist",k:"key",c:"comment"};meta[map[cp[1].toLowerCase()]||cp[1].toLowerCase()]=cp[2];return true;}const on=line.match(META_RE);if(on){meta[on[1].toLowerCase()]=on[2].trim();return true;}return false;}
function capitalize(s){return String(s||"").replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());}
function parseSongText(text){const lines=String(text||"").replace(/\r\n/g,"\n").split("\n");const meta={};const sections=[];let current={name:"",lines:[]};let i=0;const leading=[];while(i<lines.length){const t=lines[i].trim();if(!t){i++;if(leading.length||Object.keys(meta).length)break;continue;}if(parseMetaLine(t,meta)){i++;continue;}if(SECTION_RE.test(t)||isChordLine(t)||/\[[A-H]/.test(t))break;if(leading.length<2){leading.push(t);i++;continue;}break;}if(!meta.title&&leading[0])meta.title=leading[0];if(!meta.artist&&leading[1])meta.artist=leading[1];while(i<lines.length){const line=lines[i];const t=line.trim();if(SECTION_RE.test(t)||(/^[A-Z][A-Za-z0-9 \-/]{0,24}:$/.test(t)&&!looksLikeChord(t.replace(":","")))){if(current.lines.length||current.name)sections.push(current);current={name:t.replace(/:$/,"").trim(),lines:[]};i++;continue;}if(!t){current.lines.push({type:"blank",parts:[]});i++;continue;}if(isChordLine(line)&&i+1<lines.length&&lines[i+1].trim()&&!isChordLine(lines[i+1])){current.lines.push({type:"lyric",parts:parseChordsOverLyrics(line,lines[i+1])});i+=2;continue;}if(isChordLine(line)){current.lines.push({type:"chords",parts:line.trim().split(/\s+/).map(c=>({chord:c,lyric:""}))});i++;continue;}if(/\[[^\]]+\]/.test(line)){current.lines.push({type:"lyric",parts:parseBracketLine(line)});i++;continue;}current.lines.push({type:"lyric",parts:[{chord:null,lyric:line}]});i++;}if(current.lines.length||current.name)sections.push(current);return {meta,sections:sections.filter(s=>s.lines.some(l=>l.type!=="blank")||s.name),source:"text"};}
function collectChords(song){const out=[];for(const sec of song.sections)for(const line of sec.lines)for(const p of line.parts||[])if(p.chord)out.push(parseChord(p.chord));return out;}
function splitLyricForInsert(lyric,count){if(count<=0)return {head:lyric,slots:[]};const text=lyric||"";if(!text.trim())return {head:"",slots:Array.from({length:count},()=>"")};const spaces=[];for(let i=1;i<text.length-1;i++)if(text[i]===" "&&text[i-1]!==" ")spaces.push(i);if(!spaces.length)return {head:text,slots:Array.from({length:count},()=>"")};const picks=[];for(let k=1;k<=count;k++)picks.push(spaces[Math.min(spaces.length-1,Math.max(0,Math.round((k/(count+1))*(spaces.length-1))))]);const cuts=[...new Set(picks)].sort((a,b)=>a-b);const chunks=[];let prev=0;for(const c of cuts){chunks.push(text.slice(prev,c));prev=c;}chunks.push(text.slice(prev));const slots=chunks.slice(1);while(slots.length<count)slots.push("");return {head:chunks[0]||"",slots:slots.slice(0,count)};}
function applyStyleToSong(song,styleId,density){const all=collectChords(song);const key=guessKey(all,song.meta.key);const flats=preferFlatsForKey(key.root,key.minor);const style=STYLES[styleId]?styleId:"bossa";const next={meta:{...song.meta,key:key.root+(key.minor?"m":""),style:STYLES[style].name,density},sections:[],key,preferFlats:flats,source:song.source};let prevPainted=null;for(const sec of song.sections){const nsec={name:sec.name,lines:[]};for(const line of sec.lines){if(line.type==="blank"){nsec.lines.push({type:"blank",parts:[]});continue;}const paintedParts=(line.parts||[]).map(part=>{if(!part.chord)return {...part,painted:null};const parsed=parseChord(part.chord);return {...part,painted:enrichQuality(parsed,style,roleFor(parsed,key))};});const partsOut=[];for(let i=0;i<paintedParts.length;i++){const part=paintedParts[i];if(!part.painted){partsOut.push({chord:null,lyric:part.lyric,generated:false});continue;}const dest=(paintedParts.slice(i+1).find(p=>p.painted)||{}).painted;let extras=[];if(dest&&density>0)extras=passingBetween(part.painted,dest,key,style,density,flats);else if(!dest&&prevPainted&&density>0&&i===0)extras=passingBetween(prevPainted,part.painted,key,style,Math.min(density,2),flats);if(dest&&extras.length){const {head,slots}=splitLyricForInsert(part.lyric||"",extras.length);partsOut.push({chord:formatChord(part.painted,flats),lyric:head,generated:false});extras.forEach((ex,e)=>partsOut.push({chord:formatChord(ex,flats),lyric:slots[e]||"",generated:true}));}else{extras.forEach(ex=>partsOut.push({chord:formatChord(ex,flats),lyric:"",generated:true}));partsOut.push({chord:formatChord(part.painted,flats),lyric:part.lyric||"",generated:false});}prevPainted=part.painted;}nsec.lines.push({type:"lyric",parts:partsOut});}next.sections.push(nsec);}return next;}
function toChordPro(song){const m=song.meta||{};const lines=[];if(m.title)lines.push(`{title: ${m.title}}`);if(m.artist)lines.push(`{artist: ${m.artist}}`);if(m.key)lines.push(`{key: ${m.key}}`);if(m.style)lines.push(`{comment: Style — ${m.style}}`);lines.push("");for(const sec of song.sections){if(sec.name)lines.push(`{comment: ${sec.name}}`);for(const line of sec.lines){if(line.type==="blank"){lines.push("");continue;}let s="";for(const p of line.parts||[]){if(p.chord)s+=`[${p.chord}]`;s+=p.lyric||"";}lines.push(s.trimEnd());}lines.push("");}return lines.join("\n").trim()+"\n";}
function toOnSong(song){return toChordPro(song).replace("{title: ","").replace("}\n{artist: ","\n").replace("}\n{key: ","\nKey: ").replace("}","");}
function toAlignedChart(song){const blocks=[];const m=song.meta||{};if(m.title)blocks.push(m.title.toUpperCase());if(m.artist)blocks.push(m.artist);if(m.key)blocks.push("Key "+m.key+(m.style?"  ·  "+m.style:""));blocks.push("");for(const sec of song.sections){if(sec.name)blocks.push(sec.name.toUpperCase());for(const line of sec.lines){if(line.type==="blank"){blocks.push("");continue;}let chordLine="",lyricLine="";for(const p of line.parts||[]){const lyric=p.lyric||"",chord=p.chord||"";if(!chord&&!lyric)continue;if(chord){if(chordLine.length<lyricLine.length)chordLine+=" ".repeat(lyricLine.length-chordLine.length);chordLine+=chord;const width=Math.max(chord.length+1,lyric.length);lyricLine+=lyric+" ".repeat(Math.max(0,width-lyric.length));chordLine+=" ".repeat(Math.max(0,width-chord.length));}else lyricLine+=lyric;}if(chordLine.trim())blocks.push(chordLine.replace(/\s+$/,""));if(lyricLine.trim()||!chordLine.trim())blocks.push(lyricLine.replace(/\s+$/,""));}blocks.push("");}return blocks.join("\n").trim()+"\n";}
function extractTextFromPdfItems(items){const rows=items.map(it=>({x:it.transform?it.transform[4]:0,y:it.transform?it.transform[5]:0,str:it.str||""}));rows.sort((a,b)=>b.y-a.y||a.x-b.x);const lines=[];for(const r of rows){const last=lines[lines.length-1];if(!last||Math.abs(last.y-r.y)>4)lines.push({y:r.y,parts:[{x:r.x,str:r.str}]});else last.parts.push({x:r.x,str:r.str});}return lines.map(l=>{l.parts.sort((a,b)=>a.x-b.x);return l.parts.map(p=>p.str).join(" ");}).join("\n");}
